import { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';

export function MFEducationalPanel() {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="sim-panel">
      <button
        onClick={() => setExpanded((v) => !v)}
        className="sim-panel-header w-full transition-colors hover:bg-surface-hover"
      >
        <span className="sim-panel-title">Understanding Magnetism</span>
        {expanded ? (
          <ChevronUp className="ml-auto h-4 w-4 text-star-white/40" strokeWidth={1.5} />
        ) : (
          <ChevronDown className="ml-auto h-4 w-4 text-star-white/40" strokeWidth={1.5} />
        )}
      </button>
      {expanded && (
        <div className="space-y-4 p-4">
          <Section title="What Is a Magnetic Field?">
            A magnetic field is the region of space around a magnet where magnetic forces
            can be detected. It is a vector field — at every point in space, it has both a
            direction and a magnitude. The field is generated by moving electric charges
            or by the intrinsic magnetic moments of particles.
          </Section>

          <Section title="Field Lines" equation="B = [3(m·r̂)r̂ − m] / r³">
            Field lines are a visual tool for representing the magnetic field. Each line
            shows the direction a compass needle would point at that location. The lines
            emerge from the north pole and curve around to enter the south pole, forming
            continuous closed loops. They never cross each other.
          </Section>

          <Section title="Density and Strength">
            Where field lines are close together, the field is strong. Where they spread
            apart, the field is weaker. Near the poles, the lines are most concentrated,
            which is why magnets exert their strongest force there. Adjust the field-line
            density control to see how more lines reveal finer detail.
          </Section>

          <Section title="Lines Aren't Real">
            Magnetic field lines do not physically exist as separate objects. They are a
            mathematical abstraction — a way to visualize a continuous vector field. The
            field itself exists everywhere in space, not just along the lines. The lines
            are simply paths that trace the field's direction.
          </Section>

          <Section title="The Compass Probe">
            A compass needle is a tiny magnet that aligns with the local magnetic field.
            Drag the gold probe in the 3D scene to move it around the magnet. The needle
            rotates to point along the field direction at that location, and the data panel
            shows the field's strength and direction. Notice how the needle flips direction
            as you cross from one side of the magnet to the other.
          </Section>

          <Section title="The Dipole Model" equation="B ∝ 1/r³">
            This simulation uses a magnetic dipole approximation — the simplest model of a
            bar magnet. The field falls off as the cube of the distance (1/r³), which is
            why moving the probe just a little farther from the magnet dramatically reduces
            the measured field strength. The orientation control rotates the dipole,
            showing how the field pattern turns with the magnet.
          </Section>
        </div>
      )}
    </div>
  );
}

function Section({
  title,
  equation,
  children,
}: {
  title: string;
  equation?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-1.5">
      <div className="flex items-center gap-2">
        <h4 className="font-display text-sm font-medium text-star-white">{title}</h4>
        {equation && (
          <code className="rounded border border-surface-border bg-space-900/50 px-1.5 py-0.5 font-mono text-[0.7rem] text-accent-ice">
            {equation}
          </code>
        )}
      </div>
      <p className="font-body text-xs leading-relaxed text-star-white/45">{children}</p>
    </div>
  );
}
